import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";

import "@/app/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="border flex flex-2">
      <aside className="w-80 py-2 border">
        {/* TODO: Make which of these links show up based on what kind of user is present */}
        <ol>
          <li>
            <Link href="./claim" className="lnk">
              Make Claim
            </Link>
          </li>
          <li>
            <Link href="./claim-status" className="lnk">
              Claim Status
            </Link>
          </li>
          <li>
            <Link href="./manage" className="lnk">
              Manage Claims
            </Link>
          </li>
          <li>
            <Link href="./reimburse" className="lnk">
              Reimburse Claims
            </Link>
          </li>
          <li>
            <Link href="./admin" className="lnk">
              Manage Users
            </Link>
          </li>
        </ol>
      </aside>
      <section>
        <main>{children} </main>
      </section>
    </section>
  );
}
