import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
      <section className="border flex flex-2">
        <aside className="w-80 py-2 border">
          <p>Aside</p>
          {/* TODO: Make which of these links show up based on what kind of user is present */}
          <ol>
            <li>
              <a href="./claim">Make Claim</a>
            </li>
            <li>
              <a href="./claim-status">Claim Status</a>
            </li>
            <li>
              <a href="./manage">Manage Claims</a>
            </li>
            <li>
              <a href="./reimburse">Reimburse Claims</a>
            </li>
            <li>
              <a href="./admin">Manage Users</a>
            </li>
          </ol>
        </aside>
        <section>
          <main>{children} </main>
        </section>
      </section>
    </section>
  );
}
